services:
  # Backend API Service
  - type: web
    name: expense-tracker-api
    runtime: python
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: FRONTEND_URL
        value: https://expense-tracker.bharadwajr.in

databases:
  # PostgreSQL Database
  - name: expense-tracker-db
    plan: free
    databaseName: expense_db
    user: expense_user
