"""Add icon and color columns to payment_modes

Revision ID: 3f874daf76b9
Revises: d69868818db0
Create Date: 2025-10-21 14:26:52.221807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f874daf76b9'
down_revision = 'd69868818db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_modes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_modes', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
